### ISSUE TITLE
[Feature]: DBとの連携を解除する

### ISSUE THREAD

**Issue by torkralle** [torkralle/notion_wordbook#28]
### 目的

ユーザーが間違ったAPI_KEYやDBを登録した際に削除できる

### 概要

登録したAPI_KEYをローカルから削除する

### タスクリスト

- [ ] `wordbook_info.dart` の `WordbookInfoViewModel` の state に WordbookInfo が保存されている。ここのクラスに `remove` みたいな CRUD の Delete にあたるメソッドを定義する。
- [ ] また、 `setDBInfo` の対にあたる `removeDBInfo` みたいなメソッドも定義する。
- [ ] 単語帳一覧画面で任意の単語帳カードを長押ししたら「消去」のような選択肢を表示し、それをタップすると `WordbookInfoViewModel` の remove 系のメソッドが呼ばれるようにする。

### 参考

https://github.com/HUITGroup/huit-roadmap/blob/1acb956a3626628d64385a4183e5af322740073f/app/flutter.md?plain=1#L71

* `shared_preferences`
↑規模が大きくなると適さない？key, value方式
* sqflite
* hive
* isar

**Comment by noriHanda** [comment]
「・・・」を押すと、詳細 or 削除のメニュー出す
