### ISSUE TITLE
[Feature]:  APIkeyの登録後、ダイアログを出す。

### ISSUE THREAD

**Issue by torkralle** [torkralle/notion_wordbook#33]
### 目的

ユーザーが適切に追加されたか分かる

### 概要

単語帳追加後に追加完了したダイアログを出す

### タスクリスト

- [ ] `WordbookInfoViewModel` の `setDBInfo` で、エラーチェックする
- [ ] `connecting_page.dart` の `ConnectButton` の `onTap` のところでローディングの時はローディング出して、エラーの時はエラーのスナックバーでも出すようにする。
- [ ] ロードが成功したら `WordbookInfoViewModel` の state を初期化する。

**Comment by USK314** [comment]
`screens/quiz_page/components/interrupt_message`と`screens/quiz_page/quiz_page.dart`を見ていただければいいと思います！

※今は`AlertDialog`っていうの使ってるんですけどこのページ（ https://qiita.com/coka__01/items/4c1aea5fb1646e463f91 ）の下の方の
`CupertinoAlertDialog`に変えようと思ってます
