### ISSUE TITLE
[Feature]: テーマカラー決めたファイルを作成する

### ISSUE THREAD

**Issue by USK314** [torkralle/notion_wordbook#41]
## 概要
そこの変数を使う

## Task List

- [ ]

**Comment by noriHanda** [comment]
<img width="751" alt="image" src="https://user-images.githubusercontent.com/18581236/173294162-7b554572-b78a-4075-b47d-2e5c573481fc.png">
こんな感じでThemeDataウィジェットだけ抜き出したファイル作るとよさそう
https://www.wantedly.com/companies/giftee/post_articles/328839

**Comment by noriHanda** [comment]
https://www.filledstacks.com/post/building-a-design-system-in-flutter/
この辺良さそう
