### ISSUE TITLE
単語テストの画面を作る

### ISSUE THREAD

**Issue by torkralle** [torkralle/notion_wordbook#5]
https://www.figma.com/file/TbwFAbKhvaQW8klKtDbyyh/Notion-Wordbook?node-id=6%3A40087

* riverpodを利用した状態管理も含む

## やること

- [x] #21
- [x] #22
- [x] #23
- [x] 単語帳モデルを作る（基本的に `List<Word>` と `bookClass` かな）。
- [ ] 単語帳「モード」を状態として持つ ViewModel を作成する（「単語帳A」とか「単語帳B」とかが状態となる）。この ViewModel は単語帳の GET を呼び出すメソッドも持つ。
- [ ] 単語帳の `List<Word>` の length と今解いた問題数を持つ変数から ProgressBar に与えるデータを計算して与える。そのまま数値としても出す。
- [ ] `Word` の definition を表示する Text 作る
- [ ] 選択肢は GET した同じ単語帳の別の単語をランダムで3つと、正解の単語一つを表示

**Comment by noriHanda** [comment]
## やること

- [ ] `home.dart` の `HomePage` の Column の `WordBookItem` を ListView で囲む。
- [ ] `WordBookItem` を `ListTile` で書き直す。 `InkWell` とかでタップできるようにする。
- [ ] 単語帳モデルを作る（基本的に `List<Word>` と `bookClass` かな）。
- [ ] 単語帳「モード」を状態として持つ ViewModel を作成する（「単語帳A」とか「単語帳B」とかが状態となる）。この ViewModel は単語帳の GET を呼び出すメソッドも持つ。
- [ ] 単語帳の `List<Word>` の length と今解いた問題数を持つ変数から ProgressBar に与えるデータを計算して与える。そのまま数値としても出す。
- [ ] `Word` の definition を表示する Text 作る
- [ ] 選択肢を出す

**Comment by noriHanda** [comment]
できた
