### ISSUE TITLE
modelとapi domainの設計を行う

### ISSUE THREAD

**Issue by torkralle** [torkralle/notion_wordbook#6]

**Comment by noriHanda** [comment]
@torkralle `json_serializable` 使うと build_runner 走らせないといけないからやめとこうって思ってたんですが、（`freezed` の話と同じ感じです。`freezed` も `json_serializable` を使うので）どうします？

**Comment by torkralle** [comment]
@noriHanda
なるほど。
たしかにbuild_runnner走らせるのはめんどくさそう。
結構NotionAPIのJSONめんどくさいんだけど、なんか解決方法あるかね？
